// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVLS-5aBkHXsxL07Abml72lkXeWOdeAEg',
    appId: '1:810823868813:web:ed44e4bc2fca7b82e69dc4',
    messagingSenderId: '810823868813',
    projectId: 'upfit-f23e3',
    authDomain: 'upfit-f23e3.firebaseapp.com',
    storageBucket: 'upfit-f23e3.firebasestorage.app',
    measurementId: 'G-S3HWEBEM4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5suW-OTHvHSmgIvPBd_tDlCqxl4Pfc-U',
    appId: '1:810823868813:android:0c9f4caa08f02d24e69dc4',
    messagingSenderId: '810823868813',
    projectId: 'upfit-f23e3',
    storageBucket: 'upfit-f23e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU7_SgA_WfUq3zVTIIM5tYfeH2cPwrh5c',
    appId: '1:810823868813:ios:4d62ae5201a1028ee69dc4',
    messagingSenderId: '810823868813',
    projectId: 'upfit-f23e3',
    storageBucket: 'upfit-f23e3.firebasestorage.app',
    iosBundleId: 'com.UpFit.tr',
  );
}
